/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programas;

import java.util.ArrayList;

/**
 *
 * @author hdavi
 */
public class crearJugador extends javax.swing.JFrame {

    /**
     * Creates new form crearJugador
     * @param pCantJugadores
     */
    public crearJugador(int pCantJugadores) {
        initComponents();
        cantJugadores = pCantJugadores-1;
    }
    public crearJugador(ArrayList<Jugador> pJugadores,int pCantidadJugadores) {
        
        players= pJugadores;
        cantJugadores = pCantidadJugadores;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        siguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Jugador");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Nombre del Jugador");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 53, -1, -1));

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        jPanel1.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 240, -1));

        siguiente.setBackground(new java.awt.Color(255, 255, 153));
        siguiente.setForeground(new java.awt.Color(68, 35, 3));
        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        jPanel1.add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(423, 188));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
        System.out.println(cantJugadores);
        System.out.println(players.size());
        if(players.size() == cantJugadores){
            String jnombre= campoNombre.getText();
            Jugador njugador = new Jugador(jnombre);
            players.add(njugador);
            venJuego nuevoJuego= new venJuego(players,cantJugadores+1);
            nuevoJuego.setVisible(true);
            this.dispose();  
        }
        else{
            
            String jnombre= campoNombre.getText();
            System.out.println(jnombre);
            Jugador njugador = new Jugador(jnombre);
            players.add(njugador);
            crearJugador otroJugador = new crearJugador(players,cantJugadores);
            otroJugador.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_siguienteActionPerformed

  
    private ArrayList<Jugador> players = new ArrayList<>();
    private int cantJugadores = 1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
